### ISSUE TITLE
Unable to run the application, it closes giving an error. 

### ISSUE THREAD

**Issue by Hikandy** [firecat53/networkmanager-dmenu#120]
If I even run, "networkmanager_dmenu -h"

Traceback (most recent call last):
  File "/sbin/networkmanager_dmenu", line 931, in <module>
    main()
  File "/sbin/networkmanager_dmenu", line 927, in main
    run()
  File "/sbin/networkmanager_dmenu", line 914, in run
    sel = get_selection(actions)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/sbin/networkmanager_dmenu", line 540, in get_selection
    sel = subprocess.run(command,
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1917, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dmenu'

(process:12648): GLib-GObject-CRITICAL **: 10:07:07.412: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed

(process:12648): GLib-GObject-CRITICAL **: 10:07:07.412: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed

(process:12648): GLib-GObject-CRITICAL **: 10:07:07.412: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed

(process:12648): GLib-GObject-CRITICAL **: 10:07:07.412: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

**Comment by firecat53** [comment]
Looks like your launcher of choice (dmenu) is not in your $PATH. You can put the complete path to dmenu (e.g. /usr/bin/dmenu) in the config file.

**Comment by firecat53** [comment]
Did you get this working?
