### ISSUE TITLE
Can't get 'Show wifi password' to work

### ISSUE THREAD

**Issue by izmyname** [firecat53/networkmanager-dmenu#145]
I can't get _Show wifi password_ option to work with foot terminal. When I start `networkmanager_dmenu`  from terminal and select _Show WiFi password_ option , I get the following error:

<details>

```
warn: client.c:381: /run/user/1000/foot-wayland-1.sock: failed to connect, will now try /run/user/1000/foot.sock

(process:97494): GLib-GObject-CRITICAL **: 23:59:32.392: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed

(process:97494): GLib-GObject-CRITICAL **: 23:59:32.392: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed

(process:97494): GLib-GObject-CRITICAL **: 23:59:32.392: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed

(process:97494): GLib-GObject-CRITICAL **: 23:59:32.392: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

</details>

Here's my config.

```
[editor]
 terminal = footclient
# gui_if_available = False
# gui = <name of gui editor> (Default: nm-connection-editor)
```

I tried to add  `--hold` option, but it didn't work, and I got the following error.

<details>

```

Traceback (most recent call last):
  File "/usr/bin/networkmanager_dmenu", line 1073, in <module>
    main()
  File "/usr/bin/networkmanager_dmenu", line 1069, in main
    run()
  File "/usr/bin/networkmanager_dmenu", line 1058, in run
    sel()
  File "/usr/bin/networkmanager_dmenu", line 315, in __call__
    self.func()
  File "/usr/bin/networkmanager_dmenu", line 786, in show_wifi_password
    subprocess.run([terminal, "-e", "nmcli", "device", "wifi", "show-password;",
  File "/usr/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'footclient --hold'
```

</details>

`footclient --hold -e nmcli device wifi show-password`, started from a terminal window, correctly spawns the window with the qr-code, though. Also, I tried using `foot` instead of `footclient`, but it didn't work, either.

**UPD:** I've tested the command with alacritty terminal, and it doesn't work, either.

**Comment by FelipeFMA** [comment]
I have the same issue

**Comment by firecat53** [comment]
Sorry people...haven't worked on this much lately. I did play with this as part of experimenting with hotspot support late last year and realized that trying to get terminals to pop up a QR code is oddly difficult. I want to fix this but it might require an optional dependency to get something consistent (maybe zenity?).

**Comment by izmyname** [comment]
Might, as well, just remove the 'show QR code entry' and related functionality. I mean, it isn't a big deal and networkmanager-applet doesn't do so, either.

**Comment by izmyname** [comment]
A little bit offtopic, if I may.

@firecat53 Regarding arch `PKGBUILD` and a description page - `networkmanager-applet` isn't required for networkmanager-connections gui. The latter is provided by `nm-connection-editor ` package, which is a dependency for the applet, but can be installed and function independently.

**Comment by firecat53** [comment]
Ah, nice. Didn't used to be that way! If you could open a separate issue, I'm happy to make those changes or merge a PR. Thanks!

**Comment by firecat53** [comment]
Updated both nmdm README and the Arch AUR package.

**Comment by firecat53** [comment]
I just pushed a commit to dev that will hopefully help with the show-wifi-password option. It adds a `show_pass` option to config.ini that can be configured for your specific terminal. See config.ini.example for a couple of examples. For foot I could, depending on if I want to close the window using WM keys, or any key:

```ini
[dmenu_passphrase]
show_pass = footclient --hold -e nmcli device wifi show-password
show_pass = footclient bash -c "nmcli device wifi show-password; read -n1 -p 'Press any key...'"
```

It's going to vary between terminals, as not all have a hold option and some handle quoting in odd ways.

Give it a try and let me know what you think. Thanks!

**Comment by izmyname** [comment]
No luck

```
Traceback (most recent call last):
  File "/usr/bin/networkmanager_dmenu", line 1142, in <module>
    main()
    ~~~~^^
  File "/usr/bin/networkmanager_dmenu", line 1138, in main
    run()
    ~~~^^
  File "/usr/bin/networkmanager_dmenu", line 1129, in run
    sel()
    ~~~^^
  File "/usr/bin/networkmanager_dmenu", line 360, in __call__
    self.func()
    ~~~~~~~~~^^
  File "/usr/bin/networkmanager_dmenu", line 851, in show_wifi_password
    subprocess.run(
    ~~~~~~~~~~~~~~^
        [terminal, "-e", "nmcli", "device", "wifi", "show-password;", "exec", "bash"], check=False
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/subprocess.py", line 556, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/subprocess.py", line 1038, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/subprocess.py", line 1974, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xterm'
```

And those strings appear in a terminal emulator every time, the program is closed.

```
(process:13555): GLib-GObject-CRITICAL **: 09:29:37.089: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed

(process:13555): GLib-GObject-CRITICAL **: 09:29:37.089: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed

(process:13555): GLib-GObject-CRITICAL **: 09:29:37.089: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed

(process:13555): GLib-GObject-CRITICAL **: 09:29:37.089: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

**Comment by izmyname** [comment]
Neither command works. I'm getting a notification about configuring `show_pass` and nothing happens, no errors, either.

**Comment by firecat53** [comment]
Sorry, logic error! Give the dev branch another try. Thanks!

**Comment by izmyname** [comment]
It works now.
