### ISSUE TITLE
Using with fuzzel

### ISSUE THREAD

**Issue by bhaumik-tripathi** [firecat53/networkmanager-dmenu#147]
I was trying to run the script with fuzzel, though the instructions didn't say anything about the need to necessarily configure any other values, so I have set/ uncomment the fuzzel line as follows
```
dmenu_command = fuzzel --dmenu -i
```
Other than that, I have set the following settings in their respective sections
```
wifi_icons = 󰤯󰤟󰤢󰤥󰤨
format = {name}  {sec}  {bars}
list_saved = True # (Default: False) list saved connections

obscure = True
obscure_color = #222222

rescan_delay = 30  # (seconds to wait after a wifi rescan before redisplaying the results)
```
I am pretty new to fuzzel and using scripts for different works in general. I am getting the following error:-
```
Traceback (most recent call last):
  File "/home/bhaumik/.local/bin/networkmanager_dmenu", line 1073, in <module>
    main()
    ~~~~^^
  File "/home/bhaumik/.local/bin/networkmanager_dmenu", line 1069, in main
    run()
    ~~~^^
  File "/home/bhaumik/.local/bin/networkmanager_dmenu", line 1046, in run
    list_saved = CONF.getboolean('dmenu', 'list_saved', fallback=False)
  File "/usr/lib64/python3.13/configparser.py", line 857, in getboolean
    return self._get_conv(section, option, self._convert_to_boolean,
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                          raw=raw, vars=vars, fallback=fallback, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/configparser.py", line 837, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     **kwargs)
                     ^^^^^^^^^
  File "/usr/lib64/python3.13/configparser.py", line 832, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib64/python3.13/configparser.py", line 1202, in _convert_to_boolean
    raise ValueError('Not a boolean: %s' % value)
ValueError: Not a boolean: True # (Default: False) list saved connections

(process:111470): GLib-GObject-CRITICAL **: 19:39:56.361: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed

(process:111470): GLib-GObject-CRITICAL **: 19:39:56.361: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed

(process:111470): GLib-GObject-CRITICAL **: 19:39:56.362: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed

(process:111470): GLib-GObject-CRITICAL **: 19:39:56.362: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

Any help would be appreciated, it may be totally possible that I could be at some fault due to my lack of soundness around fuzzel in general.

**Comment by bhaumik-tripathi** [comment]
Yep, That was the issue, thanks for helping. Closing the issue. BUT, thanks for the script, it's great btw.
