### ISSUE TITLE
Error when Wifi disabled

### ISSUE THREAD

**Issue by hottycat** [firecat53/networkmanager-dmenu#29]
I get the following error when wifi is disabled in NetworkManager

> Traceback (most recent call last):
  File "/usr/bin/networkmanager_dmenu", line 517, in <module>
    run()
  File "/usr/bin/networkmanager_dmenu", line 500, in run
    ap_actions = create_ap_actions(*create_ap_list(adapter))
  File "/usr/bin/networkmanager_dmenu", line 479, in create_ap_list
    active_ap_con = active_ap.filter_connections(conns)
AttributeError: 'NoneType' object has no attribute 'filter_connections'

**Comment by firecat53** [comment]
Thanks. I restructured some things and must have broken it... I'll take a look later..
