### ISSUE TITLE
Only able to launch program with python 3.6

### ISSUE THREAD

**Issue by zerinoid** [firecat53/networkmanager-dmenu#66]
I'm um ubuntu 18.04, when I try to launch with python2.7 I get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/networkmanager_dmenu", line 689, in <module>
    run()
  File "/usr/local/bin/networkmanager_dmenu", line 662, in run
    ap_actions = create_ap_actions(*create_ap_list(adapter, active))
  File "/usr/local/bin/networkmanager_dmenu", line 295, in create_ap_actions
    max_len_sec, bars)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128)
```
I'm changing python version by symlinking /usr/bin/python to 2.7 or 3.6

**Comment by firecat53** [comment]
See my response in the [other issue](https://github.com/firecat53/networkmanager-dmenu/issues/39#issuecomment-572350299)
